# Generated by Django 4.2.30 on 2026-06-26 10:23

import core.fields
import core.models.base_mutation
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAudience',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('planned_count', models.IntegerField(blank=True, null=True)),
                ('actual_count', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityAudienceMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
        migrations.CreateModel(
            name='CommunicationPost',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('UPDATE', 'Update'), ('MEDIA_HIGHLIGHT', 'Media Highlight'), ('NEWSLETTER', 'Newsletter')], default='ANNOUNCEMENT', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CommunicationPostMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
        migrations.CreateModel(
            name='HistoricalActivityAudience',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('planned_count', models.IntegerField(blank=True, null=True)),
                ('actual_count', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical activity audience',
                'verbose_name_plural': 'historical activity audiences',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCommunicationPost',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('UPDATE', 'Update'), ('MEDIA_HIGHLIGHT', 'Media Highlight'), ('NEWSLETTER', 'Newsletter')], default='ANNOUNCEMENT', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical communication post',
                'verbose_name_plural': 'historical communication posts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStakeholderType',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('NATIONAL', 'National'), ('REGIONAL', 'Regional'), ('PAA', 'PAA (Project Area Authority)'), ('COMMUNITY', 'Community'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical stakeholder type',
                'verbose_name_plural': 'historical stakeholder types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StakeholderType',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', null=True)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('NATIONAL', 'National'), ('REGIONAL', 'Regional'), ('PAA', 'PAA (Project Area Authority)'), ('COMMUNITY', 'Community'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StakeholderTypeMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
        migrations.RemoveField(
            model_name='communicationactivity',
            name='audience_size',
        ),
        migrations.RemoveField(
            model_name='historicalcommunicationactivity',
            name='audience_size',
        ),
        migrations.AddField(
            model_name='communicationactivity',
            name='activity_type',
            field=models.CharField(choices=[('MEDIA_MISSION', 'Media Mission'), ('PRESS_RELEASE', 'Press Release'), ('PRESS_CONFERENCE', 'Press Conference'), ('IMPACT_CASE_STUDY', 'Impact Case Study'), ('NEWSLETTER', 'Newsletter'), ('ANNUAL_REPORT', 'Annual Report'), ('COMMUNITY_AWARENESS', 'Community Awareness Session'), ('STAKEHOLDER_BRIEFING', 'Stakeholder Briefing'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='communicationactivity',
            name='actual_audience_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationactivity',
            name='media_houses_invited',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationactivity',
            name='media_houses_reported',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationactivity',
            name='planned_audience_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationactivity',
            name='virtual_platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommunicationactivity',
            name='activity_type',
            field=models.CharField(choices=[('MEDIA_MISSION', 'Media Mission'), ('PRESS_RELEASE', 'Press Release'), ('PRESS_CONFERENCE', 'Press Conference'), ('IMPACT_CASE_STUDY', 'Impact Case Study'), ('NEWSLETTER', 'Newsletter'), ('ANNUAL_REPORT', 'Annual Report'), ('COMMUNITY_AWARENESS', 'Community Awareness Session'), ('STAKEHOLDER_BRIEFING', 'Stakeholder Briefing'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='historicalcommunicationactivity',
            name='actual_audience_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommunicationactivity',
            name='media_houses_invited',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommunicationactivity',
            name='media_houses_reported',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommunicationactivity',
            name='planned_audience_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommunicationactivity',
            name='virtual_platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='communicationactivity',
            index=models.Index(fields=['activity_type'], name='communicati_activit_469499_idx'),
        ),
        migrations.AddField(
            model_name='stakeholdertypemutation',
            name='mutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stakeholder_types', to='core.mutationlog'),
        ),
        migrations.AddField(
            model_name='stakeholdertypemutation',
            name='stakeholder_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='communications.stakeholdertype'),
        ),
        migrations.AddField(
            model_name='stakeholdertype',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stakeholdertype',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstakeholdertype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstakeholdertype',
            name='user_created',
            field=models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalstakeholdertype',
            name='user_updated',
            field=models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcommunicationpost',
            name='activity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='communications.communicationactivity'),
        ),
        migrations.AddField(
            model_name='historicalcommunicationpost',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcommunicationpost',
            name='user_created',
            field=models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcommunicationpost',
            name='user_updated',
            field=models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalactivityaudience',
            name='activity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='communications.communicationactivity'),
        ),
        migrations.AddField(
            model_name='historicalactivityaudience',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalactivityaudience',
            name='stakeholder_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='communications.stakeholdertype'),
        ),
        migrations.AddField(
            model_name='historicalactivityaudience',
            name='user_created',
            field=models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalactivityaudience',
            name='user_updated',
            field=models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationpostmutation',
            name='communication_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='communications.communicationpost'),
        ),
        migrations.AddField(
            model_name='communicationpostmutation',
            name='mutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='communication_posts', to='core.mutationlog'),
        ),
        migrations.AddField(
            model_name='communicationpost',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='communications.communicationactivity'),
        ),
        migrations.AddField(
            model_name='communicationpost',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationpost',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityaudiencemutation',
            name='activity_audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='communications.activityaudience'),
        ),
        migrations.AddField(
            model_name='activityaudiencemutation',
            name='mutation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_audiences', to='core.mutationlog'),
        ),
        migrations.AddField(
            model_name='activityaudience',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='audiences', to='communications.communicationactivity'),
        ),
        migrations.AddField(
            model_name='activityaudience',
            name='stakeholder_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_audiences', to='communications.stakeholdertype'),
        ),
        migrations.AddField(
            model_name='activityaudience',
            name='user_created',
            field=models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityaudience',
            name='user_updated',
            field=models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stakeholdertype',
            index=models.Index(fields=['code'], name='communicati_code_9e304a_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholdertype',
            index=models.Index(fields=['level'], name='communicati_level_4e9414_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholdertype',
            index=models.Index(fields=['is_active'], name='communicati_is_acti_6bb1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationpost',
            index=models.Index(fields=['post_type'], name='communicati_post_ty_9bba8d_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationpost',
            index=models.Index(fields=['is_published'], name='communicati_is_publ_d52fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationpost',
            index=models.Index(fields=['published_at'], name='communicati_publish_112d75_idx'),
        ),
        migrations.AddIndex(
            model_name='activityaudience',
            index=models.Index(fields=['activity'], name='communicati_activit_49a12d_idx'),
        ),
        migrations.AddIndex(
            model_name='activityaudience',
            index=models.Index(fields=['stakeholder_type'], name='communicati_stakeho_6020f2_idx'),
        ),
    ]
