# Generated by Django 4.2.30 on 2026-07-21 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_activity_code_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationpostattachment',
            name='is_inline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcommunicationpostattachment',
            name='is_inline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communicationpostattachment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='communications.communicationpost'),
        ),
    ]
